Target should be linked with dvdcss when the definition HAVE_DVDCSS_DVDCSS_H is set
The commit fixes the following error, trying to link libmythdvdnav.

/usr/bin/ld: ../../../../external/libmythdvdnav/libmythdvdnav-35.so.35.0: undefined reference to `dvdcss_open'
/usr/bin/ld: ../../../../external/libmythdvdnav/libmythdvdnav-35.so.35.0: undefined reference to `dvdcss_close'
/usr/bin/ld: ../../../../external/libmythdvdnav/libmythdvdnav-35.so.35.0: undefined reference to `dvdcss_open_stream'
/usr/bin/ld: ../../../../external/libmythdvdnav/libmythdvdnav-35.so.35.0: undefined reference to `dvdcss_read'
/usr/bin/ld: ../../../../external/libmythdvdnav/libmythdvdnav-35.so.35.0: undefined reference to `dvdcss_seek'
collect2: error: ld returned 1 exit status